### ISSUE TITLE
应用页面添加组件-从应用市场安装-搜索后UI不显示搜索结果

### ISSUE THREAD

**Issue by barnettZQG** [goodrain/rainbond-ui#166]
![image](https://user-images.githubusercontent.com/18493394/61210081-f9edf800-a72d-11e9-9691-e5ae892d69af.png)

- [x] Rainbond Version: 5.1.5

**Comment by zsl1549** [comment]
Failure to add scopeMax="localApplication" results in

**Comment by barnettZQG** [comment]
#172

**Comment by barnettZQG** [comment]
Resolve by PR #167
