### ISSUE TITLE
版本管理中，失败的构建记录不应该有升级操作

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond-ui#168]
![image](https://user-images.githubusercontent.com/33855684/61603589-b4bb5000-ac70-11e9-888d-2ee1a2cfe4e1.png)
如图，并如题

**Comment by zsl1549** [comment]
@GLYASAI  需要看下构建版本信息  upgrade_or_rollback字段为1 升级 出现

**Comment by GLYASAI** [comment]
当构建版本状态为失败, 且大于当前运行版本时, upgrade_or_rollback 的值为'2'.
如果 upgrade_or_rollback 等于 2, 没有升级或回滚操作, 当时应该有'删除'操作, 区别于'0'
