### ISSUE TITLE
java源码构建，页面应该指定为自定义JDK地址

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond-ui#169]
![image](https://user-images.githubusercontent.com/33855684/61863148-a33ca700-af01-11e9-99cd-d38868c6dbe3.png)
如图，图中的文字显示为ORACLEJDK地址，以及是否启用ORACLEJDK等字样，请更改为自定义JDK 。OracleJDK也作为自定义JDK中的一种。

**Comment by zsl1549** [comment]
已修复 请查看 https://github.com/goodrain/rainbond-ui/pull/176

**Comment by zsl1549** [comment]
已修复 请查看 https://github.com/goodrain/rainbond-ui/pull/176

**Comment by barnettZQG** [comment]
未改进

**Comment by barnettZQG** [comment]
已修改为 内置OpenJDK和自定义JDK 选择。
