### ISSUE TITLE
依赖上游应用的连接信息显示不全

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond-ui#171]
![image](https://user-images.githubusercontent.com/33855684/62280145-eeb10100-b47d-11e9-95fc-4419139006bb.png)

如图，连接信息里应该有6个环境变量，但是只显示5个，没有分页

**Comment by zsl1549** [comment]
已修改https://github.com/goodrain/rainbond-ui/pull/173 新增分页功能 每页展示8条
