### ISSUE TITLE
从应用市场安装应用失败

### ISSUE THREAD

**Issue by fanyangyang** [goodrain/rainbond-ui#172]
在项目构建过程中，从我的应用->添加服务组件->从应用市场开始 选择MySQL 5.5.61 (单机版)进行安装会提示请求错误（请求云市错误）

如下图

![image](https://user-images.githubusercontent.com/14025359/62285149-a0a0fb00-b487-11e9-861e-5c294198684c.png)

**Comment by barnettZQG** [comment]
基于内部云市安装-搜索也不能使用。
