### ISSUE TITLE
分享服务到团队中, 报"应用市场主服务服务缺少依赖服务，请添加依赖服务，或强制执行"

### ISSUE THREAD

**Issue by GLYASAI** [goodrain/rainbond-ui#186]
- rainbond版本: 5.1.6-release

![image](https://user-images.githubusercontent.com/21967570/63767772-19696a80-c901-11e9-93e5-7267a6c20765.png)

![image](https://user-images.githubusercontent.com/21967570/63767872-56cdf800-c901-11e9-88d6-785682a27735.png)

接口地址: http://console.goodrain.com/console/teams/23ehgni5/share/434/info?use_force=false

当用户确认取消依赖后, 点击确认分享时, use_force应该为true

**Comment by zsl1549** [comment]
fix https://github.com/goodrain/rainbond-ui/pull/198
