### ISSUE TITLE
应用发布到应用市场时添加的应用图标无法预览

### ISSUE THREAD

**Issue by Aaron-23** [goodrain/rainbond-ui#215]
![image](https://user-images.githubusercontent.com/50609288/65415198-d7601580-de27-11e9-9b46-fa68d80ac7a5.png)

![image](https://user-images.githubusercontent.com/50609288/65415237-efd03000-de27-11e9-8fb5-2d983b1c6856.png)

**Comment by zsl1549** [comment]
fix https://github.com/goodrain/rainbond-ui/pull/222
