### ISSUE TITLE
从管理后台扩容节点时如果选择不安装，在点击确定后没有安装按钮，就无法安装了

### ISSUE THREAD

**Issue by Aaron-23** [goodrain/rainbond-ui#216]
![image](https://user-images.githubusercontent.com/50609288/65569157-296f7b00-df8f-11e9-891a-c0b65ddf2a71.png)
![Uploading image.png…]()

**Comment by dazuimao1990** [comment]
附加一点，管理后台安装日志是需要打印出来的
