### ISSUE TITLE
监听所有IP（0.0.0.0）时，访问界面没有给出合适的访问路径

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond-ui#218]
新版本网关在监听所有IP（0.0.0.0）时，访问界面没有给出合适的访问路径，而给出 0.0.0.0：
20002 这样的访问地址，用户不知道怎么正确访问。
![image](https://user-images.githubusercontent.com/33855684/66368791-40b95a00-e9cc-11e9-91e3-325dc5988cc7.png)

**Comment by zsl1549** [comment]
fix https://github.com/goodrain/rainbond-ui/pull/225
