### ISSUE TITLE
企业版不应出现的提示

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond-ui#219]
![image](https://user-images.githubusercontent.com/33855684/66369284-5a5ba100-e9ce-11e9-85ed-c0c87e8aa5bd.png)

团队管理 —— 数据中心 —— 开通数据中心
这个页面下，对企业版本不应再有图中的提示

**Comment by zsl1549** [comment]
fix https://github.com/goodrain/rainbond-ui/pull/220

**Comment by zsl1549** [comment]
fix https://github.com/goodrain/rainbond-ui/pull/227
