### ISSUE TITLE
端口是否打开的判断有误

### ISSUE THREAD

**Issue by GLYASAI** [goodrain/rainbond-ui#241]
- Rainbond Version: v5.1.8-beta-c58f4ae-2019-10-15-15

![image](https://user-images.githubusercontent.com/21967570/66912825-eb252300-f045-11e9-9641-3788580244bc.png)

对外端口已经打开, 点击访问按钮, 提示"http协议端口需打开外部访问服务, 去打开".

复现步骤:
1. 创建一个nginx, 不打开对外端口
2. 在访问策略中为该nginx添加一条 TCP 策略, 这时会提示打开对外端口, 点击打开
3. 回到nginx组件的页面, 点击访问

**Comment by zsl1549** [comment]
access_type 类型为 http_port
![image](https://user-images.githubusercontent.com/32888522/70773675-11034580-1db3-11ea-82c5-9689ba3358e6.png)
