### ISSUE TITLE
git仓库地址校验有误

### ISSUE THREAD

**Issue by GLYASAI** [goodrain/rainbond-ui#245]
https://gitee.com/jeecg/jeecg-boot, 这个地址是可以拉代码的, 如下图:

![image](https://user-images.githubusercontent.com/21967570/67022252-83e59c80-f133-11e9-8545-a9305c18ea9e.png)

但是在源码创建时, 却说**仓库地址不合法**, 如下图:

![image](https://user-images.githubusercontent.com/21967570/67022481-df178f00-f133-11e9-8a68-af87013da0de.png)

**Comment by zsl1549** [comment]
/^(git@|svn:\/\/|http:\/\/|https:\/\/).+$/gi  修改校验规则

**Comment by zsl1549** [comment]
fix https://github.com/goodrain/rainbond-ui/pull/247
