### ISSUE TITLE
选中一个应用, 另外一个应用也会被选中

### ISSUE THREAD

**Issue by GLYASAI** [goodrain/rainbond-ui#246]
![image](https://user-images.githubusercontent.com/21967570/67064088-be831f80-f19b-11e9-9fa1-d39ba87c1bba.png)

如图, 选中应用"multimodule"的时候, 应用"测试硬"也被选中了.

**Comment by GLYASAI** [comment]
![image](https://user-images.githubusercontent.com/21967570/67064198-2b96b500-f19c-11e9-82ae-cd9cc96a84db.png)

**Comment by zsl1549** [comment]
goodrain/rainbond-ui #248

**Comment by zsl1549** [comment]
[https://github.com/goodrain/rainbond-ui/pull/248](url)

**Comment by zsl1549** [comment]
fix #248

**Comment by zsl1549** [comment]
[](url)
