### ISSUE TITLE
安装插件需要有判断与限制

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond-ui#265]
根据插件的类型，应该禁止如下情况的插件一同安装：

- 出口网络 与 出口网络
- 入口网络 与 入口网络
- 出入口共治 与 出入口共治
- 出入口共治 与 入口网络
- 出入口共治 与 出口网络

**Comment by dazuimao1990** [comment]
附加一个需求：
对于只有tcp/udp协议端口的服务组件，应该禁止其安装服务实时性能分析插件。
并在禁止的同时提示信息： 服务实时性能分析插件仅支持 http 与 mysql 协议。

**Comment by barnettZQG** [comment]
@dazuimao1990 请于5.1.9环境验证。
