### ISSUE TITLE
java-maven多模块构建的服务组件，执行重新检测会有问题

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond-ui#269]
如题，对于一个 java-maven多模块构建的服务组件，在构建源页面执行重新检测后，会略过选择模块步骤，并修改组件的构建命令和启动命令。再构建就会构建成为另一个模块。这里要有比较稳妥的限制。

- 要么，不允许来自多模块构建的服务组件改变构建命令和启动命令（语言类型识别为非Java-Maven的情况除外）。
- 要么，识别出多模块就还得让人家选要构建的模块。

**Comment by barnettZQG** [comment]
@dazuimao1990 请于5.1.9环境测试验证
