### ISSUE TITLE
nodejsstatic项目源码构建的界面优化

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond-ui#272]
如题，这是一个新的需求，对于由nodejsstatic源码构建的应用，其构建源页面要有新的优化。

添加多个配置项：

- 选择node版本，默认8.12.0，其他可选项具体做的时候可以来问我；一旦被选定，则配置对应的环境变量 BUILD_RUNTIMES

- 指定npm私服地址，默认值为“https://registry.npm.taobao.org”，一旦有用户自定义，则传入对应的环境变量 BUILD_NPM_REGISTRY 和 BUILD_YARN_REGISTRY

- 指定静态文件构建命令，默认值为 “npm run build” 或 “yarn run build”，一旦有用户自定义，则传入环境变量 BUILD_NPM_BUILD_CMD 和 BUILD_YARN_BUILD_CMD 

- 指定node构建环境，默认值是"production"，一旦有用户自定义，则传入环境变量 BUILD_NODE_ENV

- 指定启动命令，默认值是“sh boot.sh”，一旦有用户自定义，则传入环境变量BUILD_PROCFILE

样式参考java-maven源码构建的构建源页面

**Comment by barnettZQG** [comment]
定义构建命令使用 BUILD_NODE_BUILD_CMD 参数，不区分npm 或者 yarn。

**Comment by barnettZQG** [comment]
V5.2版本中支持。
