### ISSUE TITLE
获取企业信息时找不到数据中心

### ISSUE THREAD

**Issue by GLYASAI** [goodrain/rainbond-ui#278]
rainbond 版本: v5.1.9-alpha

![image](https://user-images.githubusercontent.com/21967570/70601165-71b44600-1c2c-11ea-97bd-c27a334ae057.png)

目前的情况是, 没有选择数据中心, 去调用 `/console/enterprise/info` 接口时, 传的 X_REGION_NAME 是  no-region, 导致找不到数据中心.

![image](https://user-images.githubusercontent.com/21967570/70601761-bf7d7e00-1c2d-11ea-90cf-e4aceedb12ff.png)

建议, 在没有选择数据中心时, 不应该去调用 `/console/enterprise/info` 接口.

**Comment by zsl1549** [comment]
请提供复现的地址 方便我调试

**Comment by zsl1549** [comment]
fix https://github.com/goodrain/rainbond-ui/pull/284
