### ISSUE TITLE
应用分享至应用市场，点击提交后跳转至此页面

### ISSUE THREAD

**Issue by Aaron-23** [goodrain/rainbond-ui#298]
共有应用还是私有应用都会跳转至此页面

![image](https://user-images.githubusercontent.com/50609288/71469949-a1a34200-2805-11ea-8058-b916b3f421cc.png)

![image](https://user-images.githubusercontent.com/50609288/71469963-acf66d80-2805-11ea-8974-a58505d10be5.png)

**Comment by panda-zxs** [comment]
这部分代码已经完全改变，这个bug已经不存在
