### ISSUE TITLE
删除预设域名后无法新增域名

### ISSUE THREAD

**Issue by Gumplefik** [goodrain/rainbond-ui#3]
应用开启对外服务后，删除预设的域名后再次添加域名时，无法添加，无任何提示，定位原因：
`port.js`:
`handleAddDomain`函数中   `payload`参数`group_id`的值`showAddDomain.bind_domains`此时已经长度为0，因而showAddDomain.bind_domains[0].g_id该值获取出错，阻塞后续代码的运行

**Comment by wangchong19940101** [comment]
感谢您的关注，bug已修复。
